### ISSUE TITLE
this should be a functor parametrized by a distance function

### ISSUE THREAD

**Issue by UnixJunkie** [UnixJunkie/vp-tree#1]

**Comment by igarnier** [comment]
Do you want to preserve a polymorphic interface along the functorized one, à la Hashtbl?
(I need your code to build some agglomerative clustering algorithm on top and I'd like to have the functorial interface too)

**Comment by UnixJunkie** [comment]
I don't know.
I like simple things.
I always use polymorphic Hashtbl.

But any contribution will be welcome,
Especially if the code is clean.

**Comment by UnixJunkie** [comment]
done by @igarnier

**Comment by UnixJunkie** [comment]
finally, I got rid of the polymorphic interface: the functor is here to enforce that the distance function being used is always the same. Thanks for this contribution.

**Comment by igarnier** [comment]
You're welcome :)

2017-11-17 10:36 GMT+01:00 Francois BERENGER <notifications@github.com>:
